### ISSUE TITLE
Could not generate AIR file, java.lang.RuntimeException

### ISSUE THREAD

**Issue by stevevestal** [sireum/v3-awas#2]
The documentation doesn't match exactly what I see, but it seems pretty close to the following.

I instantiate a system implementation and make that a selection in the AADL Navigator view.

I select OSATE > Sireum HAMR > Serialize AIR to file

After a few seconds I get a popup saying "Could not generate AIR."  The console has the following stack dump.

I am using OSATE 2.9.0 on Windows 10.

Generating AIR ...
Error encountered while generating AIR
java.lang.RuntimeException: Incorrect translation!
	at org.sireum.aadl.osate.architecture.Visitor.buildConnection(Visitor.java:213)
	at org.sireum.aadl.osate.architecture.Visitor.lambda$9(Visitor.java:474)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sireum.aadl.osate.architecture.Visitor.buildComponent(Visitor.java:474)
	at org.sireum.aadl.osate.architecture.Visitor.lambda$8(Visitor.java:469)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sireum.aadl.osate.architecture.Visitor.buildComponent(Visitor.java:469)
	at org.sireum.aadl.osate.architecture.Visitor.lambda$8(Visitor.java:469)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sireum.aadl.osate.architecture.Visitor.buildComponent(Visitor.java:469)
	at org.sireum.aadl.osate.architecture.Visitor.lambda$8(Visitor.java:469)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sireum.aadl.osate.architecture.Visitor.buildComponent(Visitor.java:469)
	at org.sireum.aadl.osate.architecture.Visitor.visit(Visitor.java:125)
	at org.sireum.aadl.osate.architecture.Visitor.convert(Visitor.java:104)
	at org.sireum.aadl.osate.util.Util.getAir(Util.java:64)
	at org.sireum.aadl.osate.util.Util.getAir(Util.java:56)
	at org.sireum.aadl.osate.handlers.LaunchSireumHandler.runJob(LaunchSireumHandler.java:36)
	at org.sireum.aadl.osate.handlers.AbstractSireumHandler$1.runInWorkspace(AbstractSireumHandler.java:89)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by thari** [comment]
Can you please provide me a test case? Also, make sure that there are no errors in the instance model file. I believe it is due to feature groups in the connection with a different number of features on either end.

**Comment by stevevestal** [comment]
I can email you the project.  There are many feature groups, a number of them empty.  I'm not sure replies to email notices I receive from gethub will get to you.  I can email it to John H and ask him to pass it along if that works.

**Comment by thari** [comment]
My email address and contact information are on the project webpage. Passing through John H works too!
